module.exports = [
    'ObjectID',
    'Name',
    'Description',
    'Schedule.ID',
    'CustomerKey',
    'Client.ID',
    'IsActive',
    'CreatedDate',
    'Client.CreatedBy',
    'ModifiedDate',
    'Client.ModifiedBy',
    'Status',
    'Client.EnterpriseID',
];
