module.exports = [
    'ObjectID',
    'PartnerKey',
    'CustomerKey',
    'Name',
    'DefaultValue',
    'MaxLength',
    'IsRequired',
    'Ordinal',
    'IsPrimaryKey',
    'FieldType',
    'CreatedDate',
    'ModifiedDate',
    'Scale',
    'Client.ID',
    'DataExtension.CustomerKey',
    'StorageType',
];
